#! /bin/sh
if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus true

#autostart applications
sh ~/scripts/1floating &
sh ~/scripts/bar_notifyd &
mopidy &
xsetroot -cursor_name left_ptr &
